spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sd_database_1?useSSL=false
    username: root
    password: 123


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
